"""phase 1 scheduling agent schema

Revision ID: c773e7461331
Revises: b7e6ded3dcf8
Create Date: 2026-01-12 23:35:42.070136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c773e7461331'
down_revision: Union[str, None] = 'b7e6ded3dcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commute_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('morning_commute_start', sa.Time(), nullable=True),
    sa.Column('morning_commute_end', sa.Time(), nullable=True),
    sa.Column('evening_commute_start', sa.Time(), nullable=True),
    sa.Column('evening_commute_end', sa.Time(), nullable=True),
    sa.Column('preferred_podcast_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_music_genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('chore_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meals_enabled', sa.Boolean(), nullable=True),
    sa.Column('meal_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('breakfast_time', sa.Time(), nullable=True),
    sa.Column('lunch_time', sa.Time(), nullable=True),
    sa.Column('dinner_time', sa.Time(), nullable=True),
    sa.Column('meal_time_flexibility_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('change_type', sa.Enum('initial', 'rebalance', 'manual_edit', 'task_incomplete', name='changetype'), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('previous_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('suggested_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'partially_accepted', name='suggestionstatus'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('importance_level', sa.Enum('low', 'medium', 'high', name='importancelevel'), nullable=True),
    sa.Column('preferred_time_start', sa.Time(), nullable=True),
    sa.Column('preferred_time_end', sa.Time(), nullable=True),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('workout_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_completion_feedback',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_preferences', sa.Column('bed_time', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('focus_time_start', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('focus_time_end', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('blocked_apps', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('user_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_preferences', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_preferences', 'blocked_apps')
    op.drop_column('user_preferences', 'focus_time_end')
    op.drop_column('user_preferences', 'focus_time_start')
    op.drop_column('user_preferences', 'bed_time')
    op.drop_table('task_completion_feedback')
    op.drop_table('workout_preferences')
    op.drop_table('schedule_suggestions')
    op.drop_table('schedule_history')
    op.drop_table('meal_preferences')
    op.drop_table('commute_preferences')
    # ### end Alembic commands ###
