"""add_commute_method_column

Revision ID: 899d1a13202d
Revises: 94ca89d8dafa
Create Date: 2026-01-17 12:07:30.317781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899d1a13202d'
down_revision: Union[str, None] = '94ca89d8dafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('commute_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'commute_method')
    # ### end Alembic commands ###
