"""add podcast_languages

Revision ID: 0569e18e0d5d
Revises: 45490efc8e93
Create Date: 2026-01-25 15:02:46.802326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0569e18e0d5d'
down_revision: Union[str, None] = '45490efc8e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('podcast_languages', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'podcast_languages')
    # ### end Alembic commands ###
